"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'y8lshea$k&-o9d*wy!yipoegcgoc@66t^v8k+esb822z!5h+4#')


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = bool(os.environ.get('DJANGO_DEBUG', True))


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    'bootstrap3',
    'accounts',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
APPEND_SLASH = False

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CONN_MAX_AGE = 10

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static_files")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

DEBUG = False


"""Если True, SecurityMiddleware устанавливает заголовок X-Content-Type-Options: nosniff во всех ответах, 
у которых его еще нет."""
SECURE_CONTENT_TYPE_NOSNIFF = True


"""Если True, SecurityMiddlewareустанавливает X-XSS-Protection: 1; mode = заголовок блока для всех ответов, 
у которых его еще нет."""
SECURE_BROWSER_XSS_FILTER = True


"""Если True, перенаправляет все не-HTTPS-запросы на HTTPS (за исключением тех URL-адресов, которые соответствуют 
регулярному выражению, указанному в ).SecurityMiddleware SECURE_REDIRECT_EXEMPT"""
SECURE_SSL_REDIRECT = True


"""Использовать ли безопасный cookie для cookie сеанса. Если для этого параметра установлено значение True«cookie», 
оно будет помечено как «безопасное», что означает, что браузеры могут гарантировать, что файл cookie отправляется 
только по HTTPS-соединению.
Отключение этого параметра не является хорошей идеей, поскольку злоумышленник может перехватить незашифрованный 
файл cookie сеанса с помощью анализатора пакетов и использовать файл cookie для перехвата сеанса пользователя."""
SESSION_COOKIE_SECURE = True

"""Использовать ли безопасный файл cookie для файла CSRF. Если для этого параметра установлено значение True«cookie», 
оно будет помечено как «безопасное», что означает, что браузеры могут гарантировать, 
что файл cookie отправляется только с подключением HTTPS."""
CSRF_COOKIE_SECURE = True

"""По умолчанию: 'SAMEORIGIN'

Значение по умолчанию для заголовка X-Frame-Options используется XFrameOptionsMiddleware. 
Смотрите документацию по защите от кликджекинга ."""
X_FRAME_OPTIONS = 'DENY'

# SECURE_HSTS_SECONDS = 300


"""
После настройки HTTPS включите следующие параметры.

CSRF_COOKIE_SECURE¶
Установите это, чтобы True избежать случайной передачи файла cookie CSRF через HTTP.

SESSION_COOKIE_SECURE¶
Установите это, чтобы True избежать случайной передачи cookie сеанса по HTTP.
"""

