# Generated by Django 2.1.7 on 2019-03-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='phone',
            field=models.CharField(default=998979999999, help_text='Telefon nomerini iriting...', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='data',
            field=models.FileField(upload_to='json_data'),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='title',
            field=models.CharField(help_text="Ob'ekt Nomini kiriting...", max_length=100),
        ),
        migrations.AlterField(
            model_name='wavedata',
            name='data',
            field=models.FileField(upload_to='wave_data'),
        ),
    ]
