# Generated by Django 2.1.7 on 2019-03-18 11:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190318_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='data',
            field=models.FileField(help_text='JSON файлни танланг...', upload_to='json_data'),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='perm_users',
            field=models.ManyToManyField(blank=True, related_name='json_dates', to=settings.AUTH_USER_MODEL),
        ),
    ]
